### ISSUE TITLE
Ugly faust2xxx pages

### ISSUE THREAD

**Issue by sletz** [grame-cncm/faustdoc#1]
After the last update, the `faust2xxxpages` (see https://faustdoc.grame.fr/manual/tools/) are a bit ugly. I guess the automatic generation tool has to be fixed?

**Comment by dfober** [comment]
Works correctly on my side (updated just before checking). Did you run `make all`?

**Comment by dfober** [comment]
I've regenerated the site and updated to the last public version of faust (for the compiler options)
